export const LOAD_LOCATION = "LOAD_LOCATION";
export const LOAD_LOCATION_START = "LOAD_LOCATION_START";
export const LOAD_LOCATION_SUCCESS = "LOAD_LOCATION_SUCCESS";
export const LOAD_LOCATION_FAILED = "LOAD_LOCATION_FAILED";
